// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/utils/logger';

// Validate required environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  throw new Error('VITE_SUPABASE_URL environment variable is required');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY environment variable is required');
}

// Safe storage access for build-time compatibility
const storage = typeof window !== 'undefined' ? localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
    fetch: async (url, options = {}) => {
      // Add timeout wrapper for all requests
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15 second timeout

      try {
        const response = await fetch(url, {
          ...options,
          signal: controller.signal,
        });
        clearTimeout(timeoutId);
        return response;
      } catch (error: any) {
        clearTimeout(timeoutId);
        
        // Log connection errors for debugging
        if (error.name === 'AbortError') {
          logger.warn('Supabase request timeout', { url });
        } else if (error.message?.includes('ERR_CONNECTION_CLOSED')) {
          logger.warn('Supabase connection closed', { url });
        }
        
        throw error;
      }
    },
  },
});

// Enhanced database utilities with retry logic and error handling
export class DatabaseUtils {
  private static retryWithBackoff = async <T>(
    fn: () => Promise<T>,
    maxRetries: number = 3,
    baseDelay: number = 1000,
    context: string = 'database operation',
  ): Promise<T> => {
    let lastError: any;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        logger.debug(`Database: Attempting ${context}`, { attempt: attempt + 1, maxRetries });
        return await fn();
      } catch (error) {
        lastError = error;
        logger.warn(`Database: ${context} failed`, {
          attempt: attempt + 1,
          maxRetries,
          error: lastError?.message || 'Unknown error',
          code: lastError?.code,
        });

        if (attempt === maxRetries) {
          logger.error(`Database: ${context} failed after ${maxRetries + 1} attempts`, {
            error: lastError?.message,
            code: lastError?.code,
            stack: lastError?.stack,
          });
          break;
        }

        // Exponential backoff with jitter
        const delay = baseDelay * Math.pow(2, attempt) + Math.random() * 1000;
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }

    throw lastError;
  };

  static async safeQuery<T>(
    queryFn: () => Promise<{ data: T | null; error: any }>,
    context: string = 'database query',
    nullChecks: boolean = true,
  ): Promise<T> {
    try {
      const result = await this.retryWithBackoff(queryFn, 3, 1000, context);

      if (result.error) {
        logger.error(`Database: Query error in ${context}`, {
          error: result.error.message,
          code: result.error.code,
          details: result.error.details,
        });
        throw result.error;
      }

      if (nullChecks && result.data === null) {
        logger.warn(`Database: No data returned from ${context}`);
        throw new Error(`No data returned from ${context}`);
      }

      return result.data as T;
    } catch (error) {
      logger.error(`Database: Safe query failed for ${context}`, { error });
      throw error;
    }
  }

  static async safeInsert(
    table: string,
    data: any,
    context: string = 'database insert',
  ): Promise<any> {
    return this.safeQuery(
      async () => {
        const result = await supabase.from(table as any).insert(data).select().single();
        return result;
      },
      context,
    );
  }

  static async safeUpsert(
    table: string,
    data: any,
    context: string = 'database upsert',
    onConflict?: string,
  ): Promise<any> {
    return this.safeQuery(
      async () => {
        const query = supabase.from(table as any).upsert(data, {
          onConflict: onConflict,
          ignoreDuplicates: false,
        }).select().single();
        return await query;
      },
      context,
    );
  }

  static async safeUpdate(
    table: string,
    data: any,
    matchConditions: any,
    context: string = 'database update',
  ): Promise<any> {
    return this.safeQuery(
      async () => {
        const result = await supabase.from(table as any).update(data).match(matchConditions).select().single();
        return result;
      },
      context,
    );
  }

  static async safeSelect(
    table: string,
    selectQuery: string,
    matchConditions: any,
    context: string = 'database select',
  ): Promise<any[]> {
    return this.safeQuery(
      async () => {
        const result = await supabase.from(table as any).select(selectQuery).match(matchConditions);
        return result;
      },
      context,
      false,
    );
  }

  static async safeDelete(
    table: string,
    matchConditions: any,
    context: string = 'database delete',
  ): Promise<void> {
    await this.retryWithBackoff(async () => {
      const { error } = await supabase.from(table as any).delete().match(matchConditions);
      if (error) throw error;
    }, 2, 500, context);
  }

  static handleConnectionError(error: any): never {
    logger.error('Database: Connection error detected', {
      error: error?.message,
      code: error?.code,
      hint: error?.hint,
    });

    if (error?.code === 'PGRST301') {
      throw new Error('Database connection timeout. Please check your internet connection.');
    } else if (error?.code === 'PGRST000') {
      throw new Error('Database connection failed. Please try again later.');
    } else if (error?.message?.includes('network')) {
      throw new Error('Network error. Please check your internet connection.');
    }

    throw error;
  }
}