export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
  tags: string[];
}

export const blogPosts: BlogPost[] = [
  {
    id: "power-hitting-tennis-ball-cricket",
    title: "Mastering Power Hitting in Tennis Ball Cricket",
    excerpt: "Power hitting depends less on brute strength and more on a refined blend of timing, bat speed, balance, and controlled aggression.",
    content: `
## Overview

Power hitting in tennis ball cricket depends less on brute strength and more on a refined blend of timing, bat speed, balance, and controlled aggression. The lighter ball rewards precision but punishes mistimed swings. This article breaks down the technical and biomechanical components of consistent power hitting.

## Key Concepts

### 1. Stance and Stability
A stable base is essential. Tennis-ball surfaces are usually uneven, so the stance should be slightly wider than shoulder-width, knees relaxed, and weight balanced on the balls of the feet.

### 2. Grip and Backlift
A neutral grip allows better bat acceleration. A higher backlift creates a longer swing arc, increasing power.

### 3. Bat Speed Mechanics
Because the ball is lighter, the energy transfer comes primarily from bat acceleration generated by:
*   Hip rotation
*   Wrist snap
*   Compact swing path

### 4. Timing Over Force
In tennis ball cricket, hitting too hard often results in top edges. Work on delaying the downswing until the ball enters the hitting zone.

### 5. Drills to Improve Power
*   **Wall batting** for reflexes
*   **Front-foot throwdowns**
*   **Bat-speed ladder swings**
*   **Controlled slog-sweep sessions**

## Conclusion

Power hitting is a science of momentum and timing. With structured training, even amateur players can consistently clear boundaries in the T10 format.
    `,
    category: "Technique",
    author: "SSPLT10 Coach",
    date: "Dec 03, 2025",
    readTime: "4 min read",
    image: "/images/power-hitting.jpg",
    tags: ["Batting", "Power Hitting", "Drills"]
  },
  {
    id: "bowling-variations-drills",
    title: "Bowling Variations & Drills for Tennis Ball Cricket",
    excerpt: "Bowling in tennis ball cricket revolves around deception, control, and exploiting ball characteristics. Learn the core variations.",
    content: `
## Overview

Bowling in tennis ball cricket revolves around deception, control, and exploiting ball characteristics. The ball grips less on most surfaces, so seam control and release angle create your main weaponry.

## Core Variations

### 1. Cutters (Off/Leg)
Use the index or middle finger to roll the ball and create deviation after pitching.

### 2. Slower Balls
Hold the ball deeper in the palm to reduce release speed.

### 3. Swing With Taped Ball
Tape on one side increases air drag, allowing late in-swing or out-swing.

## Bowling Drills

*   **Target length cones**
*   **One-step power release drill**
*   **Wrist-position isolation drill**
*   **Taped-ball swing practice**

## Conclusion

A bowler with three solid variations becomes extremely valuable in T10 cricket.
    `,
    category: "Technique",
    author: "SSPLT10 Coach",
    date: "Dec 02, 2025",
    readTime: "3 min read",
    image: "/images/bowling-variations.jpg",
    tags: ["Bowling", "Variations", "Drills"]
  },
  {
    id: "sharpening-your-fielding",
    title: "Sharpening Your Fielding",
    excerpt: "Fielding is often the decisive factor in short-format tennis ball cricket. Rapid reaction time is critical.",
    content: `
## Overview

Fielding is often the decisive factor in short-format tennis ball cricket. With boundaries shorter and balls lighter, rapid reaction time is critical.

## Techniques

### 1. Slip & close-in catching
React fast; use soft hands and minimal movement.

### 2. Ground Fielding
Stay low, hands in front, scoop technique for skidding tennis balls.

### 3. Direct Hit Drills
Use cones or stumps as targets; focus on fast release over power.

## Agility Drills

*   **Ladder footwork**
*   **5-10-5 shuttle runs**
*   **Reaction ball catches**

## Conclusion

A sharp fielder saves 10–12 runs every match—crucial in T10.
    `,
    category: "Fielding",
    author: "SSPLT10 Coach",
    date: "Dec 01, 2025",
    readTime: "3 min read",
    image: "/images/fielding.jpg",
    tags: ["Fielding", "Agility", "Fitness"]
  },
  {
    id: "equipment-gear-guide",
    title: "Equipment & Gear Guide",
    excerpt: "Tennis ball cricket has its own gear ecosystem—lighter bats, specific ball types, and shock-absorbing footwear.",
    content: `
## Overview

Tennis ball cricket has its own gear ecosystem—lighter bats, specific ball types, and shock-absorbing footwear.

## Bat Selection

*   **Weight**: 900–1050g
*   **Sweet Spot**: Higher sweet spot for skidding bounce
*   **Edges**: Thicker edges for power-hitting stability

## Ball Types

*   **Hard tennis balls**: More bounce, faster pace
*   **Soft tennis balls**: More grip, slower pace
*   **Taped balls**: Swing, skid, better for death overs

## Footwear

Choose rubber-sole shoes with strong heel support.

## Conclusion

The right gear increases performance and reduces injury risk.
    `,
    category: "Gear",
    author: "SSPLT10 Expert",
    date: "Nov 30, 2025",
    readTime: "3 min read",
    image: "/images/gear-guide.jpg",
    tags: ["Equipment", "Bats", "Balls"]
  },
  {
    id: "fitness-training-routines",
    title: "Fitness & Training Routines",
    excerpt: "T10 tennis-ball cricket demands explosive speed, quick reflexes, and strong stabilizing muscles.",
    content: `
## Overview

T10 tennis-ball cricket demands explosive speed, quick reflexes, and strong stabilizing muscles.

## Fitness Components

*   **Speed Training**: Sprints, cone acceleration
*   **Strength**: Core, wrist, shoulder workouts
*   **Flexibility**: Dynamic warmups, cooldown stretches
*   **Endurance**: Short high-intensity intervals

## Sample Weekly Plan

*   **Mon**: Speed + Nets
*   **Tue**: Strength + Drills
*   **Wed**: Tactical practice
*   **Thu**: Agility + Throwdowns
*   **Fri**: Match simulation

## Conclusion

Fitness transforms average players into elite performers.
    `,
    category: "Fitness",
    author: "SSPLT10 Trainer",
    date: "Nov 29, 2025",
    readTime: "4 min read",
    image: "/images/fitness.jpg",
    tags: ["Fitness", "Training", "Workout"]
  },
  {
    id: "tactical-matchplay-t10",
    title: "Tactical Matchplay in T10",
    excerpt: "T10 is all about maximizing scoring phases while controlling high-risk overs. Good tactics can outperform raw talent.",
    content: `
## Overview

T10 is all about maximizing scoring phases while controlling high-risk overs.

## Tactical Areas

*   **Powerplay hitting strategy**
*   **Rotating strike in middle overs**
*   **Bowler matchup planning**
*   **Reading pitch bounce**
*   **Tape-ball death over strategy**

## Field Placement Strategy

Focus on eliminating boundary options rather than preventing singles.

## Conclusion

Good tactics can outperform raw talent in T10.
    `,
    category: "Strategy",
    author: "SSPLT10 Analyst",
    date: "Nov 28, 2025",
    readTime: "3 min read",
    image: "/images/tactics.jpg",
    tags: ["Strategy", "Tactics", "Matchplay"]
  },
  {
    id: "ssplt10-season-launch",
    title: "SSPLT10 Season Launch & Format",
    excerpt: "SSPLT10 emerges as South India’s most structured tennis-ball T10 league, designed to elevate street talent onto professional platforms.",
    content: `
## Overview

SSPLT10 emerges as South India’s most structured tennis-ball T10 league, designed to elevate street talent onto professional platforms.

## Highlights

*   **Multi-state franchise system**
*   **8-over tennis ball + 2-over tape ball format**
*   **Transparent trials**
*   **Talent hunt and player analytics**
*   **Prize pool and sponsorship impact**

## Conclusion

SSPLT10 is setting a new standard for tennis-ball cricket leagues.
    `,
    category: "News",
    author: "SSPLT10 Official",
    date: "Nov 27, 2025",
    readTime: "2 min read",
    image: "/images/season-launch.jpg",
    tags: ["News", "Launch", "League"]
  },
  {
    id: "player-spotlight",
    title: "SSPLT10 Player Spotlight",
    excerpt: "Player spotlight blogs help fans connect with emerging talents. Discover the stories behind the stars.",
    content: `
## Overview

Player spotlight blogs help fans connect with emerging talents. The structure should cover background, development, role, strengths, and statistics.

## Typical Story Flow

*   **Early gully cricket beginnings**
*   **Skill development**
*   **Trial success**
*   **Performance trends**
*   **Team role & match impact**
*   **Advice for young players**

## Conclusion

Human stories create emotional investment in the league.
    `,
    category: "Spotlight",
    author: "SSPLT10 Media",
    date: "Nov 26, 2025",
    readTime: "3 min read",
    image: "/images/player-spotlight.jpg",
    tags: ["Spotlight", "Players", "Stories"]
  },
  {
    id: "trials-community-impact",
    title: "SSPLT10 Trials & Community Impact",
    excerpt: "SSPLT10 trials are transforming community cricket by offering professional structure, analytics, and opportunities for youth.",
    content: `
## Overview

SSPLT10 trials are transforming community cricket by offering professional structure, analytics, and opportunities for youth across South India.

## Key Themes

*   **State-wise trial roadmap**
*   **Transparent video-recorded assessment**
*   **Grassroots engagement**
*   **Community camps**
*   **Talent scouting metrics**

## Conclusion

This league is building a professional future for tennis-ball cricket.
    `,
    category: "Community",
    author: "SSPLT10 Community",
    date: "Nov 25, 2025",
    readTime: "3 min read",
    image: "/images/trials.jpg",
    tags: ["Community", "Trials", "Impact"]
  }
];
