-- Local-dev only: production already has all of these. Recreates the tables and views the
-- admin area and a few public features read, so they work against the local Supabase
-- instead of returning 404s.
--   * Tables that appear in src/integrations/supabase/types.ts use exactly those columns.
--   * The rest (rewards, news_articles, user_profiles, WhatsApp, trial candidates, chat,
--     GA permissions, QR scans) are shaped from how the code reads and writes them.
--   * Views are real views over the local tables, so admin reports show local test data.
--     Their logic approximates production's; the columns match what the pages read.
-- Every table and view is created only when it is missing, so on production this file is
-- a no-op: nothing is created, replaced or granted there. (A plain "create or replace view"
-- would overwrite the real production views, which is why each one is guarded.)
-- Not recreated: the RPC functions (allocate_to_trials, get_workflow_dashboard_stats, ...)
-- and the edge functions (ga4-*, QR generation, emails); those stay unavailable locally.

-- Access rules for a table created by this file (local dev): signed-in users (the admin
-- pages) have full access; anonymous visitors can read and add rows, as public forms do.
create or replace function pg_temp.local_dev_policies(t text) returns void language plpgsql as $f$
begin
  execute format('alter table public.%I enable row level security', t);
  execute format('create policy "local dev signed-in full access" on public.%I for all to authenticated using (true) with check (true)', t);
  execute format('create policy "local dev anon read" on public.%I for select to anon using (true)', t);
  execute format('create policy "local dev anon insert" on public.%I for insert to anon with check (true)', t);
end $f$;

do $$
declare
  -- True only on a database that lacked the production schema, i.e. a local one. Guards the
  -- few statements below that change tables which already exist on production.
  local_dev boolean := to_regclass('public.rewards') is null;
begin
  ---------------------------------------------------------------------------
  -- Tables from the generated types
  ---------------------------------------------------------------------------
  if to_regclass('public.admin_invites') is null then
    create table public.admin_invites (
      created_at timestamptz,
      created_by text,
      email text primary key,
      permissions jsonb,
      role text,
      status text
    );
    perform pg_temp.local_dev_policies('admin_invites');
  end if;

  if to_regclass('public.email_logs') is null then
    create table public.email_logs (
      created_at timestamptz not null default now(),
      email text,
      email_type text,
      error_message text,
      id uuid primary key default gen_random_uuid(),
      payment_id text,
      recipient_email text,
      recipient_name text,
      registration_id text,
      sent_at timestamptz not null default now(),
      status text
    );
    perform pg_temp.local_dev_policies('email_logs');
  end if;

  if to_regclass('public.webhook_events') is null then
    create table public.webhook_events (
      event_id text unique,
      event_type text,
      id bigint generated by default as identity primary key,
      payload jsonb,
      processed_at timestamptz
    );
    perform pg_temp.local_dev_policies('webhook_events');
  end if;

  if to_regclass('public.visitor_leads') is null then
    create table public.visitor_leads (
      created_at timestamptz,
      email text,
      id uuid primary key default gen_random_uuid(),
      name text,
      page_url text,
      phone text,
      utm_campaign text,
      utm_medium text,
      utm_source text
    );
    perform pg_temp.local_dev_policies('visitor_leads');
  end if;

  if to_regclass('public.sspl_qr_codes') is null then
    create table public.sspl_qr_codes (
      channel_id text,
      code text unique,
      created_at timestamptz,
      created_by text,
      current_scans numeric,
      description text,
      expires_at timestamptz,
      id uuid primary key default gen_random_uuid(),
      is_active boolean,
      max_scans numeric,
      tags text[],
      target_url text,
      template_id text,
      title text,
      updated_at timestamptz
    );
    perform pg_temp.local_dev_policies('sspl_qr_codes');
  end if;

  if to_regclass('public.theme_settings') is null then
    create table public.theme_settings (
      colors jsonb,
      created_at timestamptz not null default now(),
      id uuid primary key default gen_random_uuid(),
      is_active boolean not null default false,
      theme_name text,
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('theme_settings');
  end if;

  if to_regclass('public.tournament_organizers') is null then
    create table public.tournament_organizers (
      area_pincode text,
      branding_support text[],
      category_other text,
      city_district text,
      created_at timestamptz not null default now(),
      current_sponsors text,
      delivery_address text,
      delivery_contact_mobile text,
      delivery_contact_name text,
      designation text,
      email text,
      end_date date,
      expected_footfall text,
      expected_teams text,
      format_other text,
      gst_number text,
      how_heard text,
      id uuid primary key default gen_random_uuid(),
      live_streaming text,
      live_streaming_link text,
      long_term_collaboration text,
      mobile_primary text,
      mobile_secondary text,
      organisation_name text,
      organiser_name text,
      preferred_ball_type text,
      remarks text,
      share_media text,
      social_facebook text,
      social_instagram text,
      social_youtube text,
      start_date date,
      state text,
      status text,
      total_tournaments text,
      tournament_category text[],
      tournament_format text,
      tournament_type text,
      tournaments_annually text,
      venue_address text,
      venue_name text
    );
    perform pg_temp.local_dev_policies('tournament_organizers');
  end if;

  if to_regclass('public.registrations') is null then
    create table public.registrations (
      amount numeric,
      created_at timestamptz,
      email text,
      id uuid primary key default gen_random_uuid(),
      name text,
      notes text,
      order_id text,
      payment_id text,
      phone text,
      player_id text,
      registration_date text,
      registration_id text,
      status text,
      trial_id text,
      updated_at timestamptz,
      utm_id text
    );
    perform pg_temp.local_dev_policies('registrations');
  end if;

  if to_regclass('public.player_workflow') is null then
    create table public.player_workflow (
      allocated_to_trials_at timestamptz,
      city text,
      confirmation_email_log_id text,
      confirmation_email_sent boolean,
      confirmation_email_sent_at timestamptz,
      created_at timestamptz not null default now(),
      email text,
      full_name text,
      moved_to_trials_at timestamptz,
      payment_amount numeric,
      payment_status text,
      phone text,
      pincode text,
      registration_id uuid references public.player_registrations (id) on delete cascade,
      state text,
      trial_uid text,
      updated_at timestamptz not null default now(),
      workflow_id uuid primary key default gen_random_uuid(),
      workflow_stage text
    );
    perform pg_temp.local_dev_policies('player_workflow');
  end if;

  if to_regclass('public.trials_allocations') is null then
    create table public.trials_allocations (
      allocation_batch text,
      allocation_date date,
      allocation_id uuid primary key default gen_random_uuid(),
      allocation_time text,
      allocation_venue text,
      attendance_status text,
      attended_at timestamptz,
      batting_score numeric,
      bowling_score numeric,
      created_at timestamptz not null default now(),
      evaluated_at timestamptz,
      evaluator_notes text,
      fielding_score numeric,
      overall_score numeric,
      remarks text,
      selection_status text,
      workflow_id uuid references public.player_workflow (workflow_id) on delete cascade
    );
    perform pg_temp.local_dev_policies('trials_allocations');
  end if;

  if to_regclass('public.trial_results') is null then
    create table public.trial_results (
      allocation_id uuid references public.trials_allocations (allocation_id) on delete cascade,
      batting_score numeric,
      bowling_score numeric,
      created_at timestamptz not null default now(),
      evaluated_at timestamptz,
      evaluated_by text,
      evaluator_notes text,
      fielding_score numeric,
      id uuid primary key default gen_random_uuid(),
      overall_score numeric,
      remarks text,
      selection_status text,
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('trial_results');
  end if;

  ---------------------------------------------------------------------------
  -- Tables shaped from the code
  ---------------------------------------------------------------------------
  if to_regclass('public.rewards') is null then
    create table public.rewards (
      id uuid primary key default gen_random_uuid(),
      title text not null,
      description text,
      points_cost integer not null default 0,
      is_active boolean not null default true,
      image_url text,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('rewards');
  end if;

  if to_regclass('public.news_articles') is null then
    create table public.news_articles (
      id uuid primary key default gen_random_uuid(),
      title text,
      slug text unique,
      excerpt text,
      content text,
      image_url text,
      is_published boolean not null default true,
      published_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('news_articles');
  end if;

  -- One row per signed-in user (id = auth user id).
  if to_regclass('public.user_profiles') is null then
    create table public.user_profiles (
      id uuid primary key references auth.users (id) on delete cascade,
      full_name text,
      email text,
      phone text,
      avatar_url text,
      referral_code text unique,
      reward_points integer not null default 0,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('user_profiles');
  end if;

  if to_regclass('public.whatsapp_campaigns') is null then
    create table public.whatsapp_campaigns (
      id uuid primary key default gen_random_uuid(),
      name text,
      message_template text,
      status text default 'DRAFT',
      instance_name text,
      daily_limit integer,
      batch_size integer,
      messages_sent_today integer default 0,
      min_delay_seconds integer,
      max_delay_seconds integer,
      total_sent integer default 0,
      total_failed integer default 0,
      started_at timestamptz,
      completed_at timestamptz,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('whatsapp_campaigns');
  end if;

  -- campaign_id is a foreign key so the page's whatsapp_campaign_recipients(count) embed works.
  if to_regclass('public.whatsapp_campaign_recipients') is null then
    create table public.whatsapp_campaign_recipients (
      id uuid primary key default gen_random_uuid(),
      campaign_id uuid not null references public.whatsapp_campaigns (id) on delete cascade,
      name text,
      mobile text,
      status text default 'PENDING',
      sent_at timestamptz,
      error_message text,
      created_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('whatsapp_campaign_recipients');
  end if;

  if to_regclass('public.trial_candidates') is null then
    create table public.trial_candidates (
      id uuid primary key default gen_random_uuid(),
      name text,
      mobile text,
      phone text,
      city text,
      state text,
      proficiency text,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('trial_candidates');
  end if;

  -- candidate_id is a foreign key so trial_progress!inner(...) embeds work.
  if to_regclass('public.trial_progress') is null then
    create table public.trial_progress (
      id uuid primary key default gen_random_uuid(),
      candidate_id uuid not null references public.trial_candidates (id) on delete cascade,
      current_level integer default 1,
      l1_called boolean default false, l1_attendance text, l1_marks numeric, l1_result text, l1_remarks text,
      l2_called boolean default false, l2_attendance text, l2_marks numeric, l2_result text, l2_remarks text,
      l3_called boolean default false, l3_attendance text, l3_marks numeric, l3_result text, l3_remarks text,
      final_status text,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('trial_progress');
  end if;

  if to_regclass('public.chat_conversations') is null then
    create table public.chat_conversations (
      id uuid primary key default gen_random_uuid(),
      session_id text not null unique,
      mobile text,
      language text,
      mode text,
      messages jsonb not null default '[]'::jsonb,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('chat_conversations');
  end if;

  if to_regclass('public.user_ga_permissions') is null then
    create table public.user_ga_permissions (
      user_id uuid primary key references auth.users (id) on delete cascade,
      permissions jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('user_ga_permissions');
  end if;

  if to_regclass('public.ga_permission_audit_log') is null then
    create table public.ga_permission_audit_log (
      id uuid primary key default gen_random_uuid(),
      changed_by text,
      target_user text,
      action text,
      permission text,
      old_value boolean,
      new_value boolean,
      changed_at timestamptz not null default now()
    );
    perform pg_temp.local_dev_policies('ga_permission_audit_log');
  end if;

  if to_regclass('public.sspl_qr_analytics') is null then
    create table public.sspl_qr_analytics (
      id uuid primary key default gen_random_uuid(),
      qr_code_id text,
      ip_address text,
      user_agent text,
      referrer text,
      scan_source text,
      scanned_at timestamptz not null default now()
    );
    create index sspl_qr_analytics_code_idx on public.sspl_qr_analytics (qr_code_id, scanned_at);
    perform pg_temp.local_dev_policies('sspl_qr_analytics');
  end if;

  ---------------------------------------------------------------------------
  -- Views (real, over the local tables)
  ---------------------------------------------------------------------------
  if to_regclass('public.v_admin_player_registrations') is null then
    create view public.v_admin_player_registrations with (security_invoker = true) as
      select id, full_name as player_name, email, phone, date_of_birth::text as date_of_birth,
             position, state, city, pincode, payment_status, payment_amount, status, created_at
      from public.player_registrations;
  end if;

  if to_regclass('public.utm_paid_users_details') is null then
    create view public.utm_paid_users_details with (security_invoker = true) as
      select id, id as registration_id, full_name as user_name, email as user_email, phone as user_phone,
             utm_source, utm_medium, utm_campaign, utm_id, payment_amount, updated_at as payment_timestamp
      from public.player_registrations
      where lower(payment_status) in ('captured', 'paid', 'completed', 'success');
  end if;

  if to_regclass('public.utm_summary') is null then
    create view public.utm_summary with (security_invoker = true) as
      select utm_source, utm_medium, utm_campaign, utm_id,
             count(*) as registrations,
             count(*) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')) as paid_registrations,
             coalesce(sum(payment_amount) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')), 0) as total_revenue,
             0::bigint as scans,
             max(updated_at) as last_activity
      from public.player_registrations
      group by utm_source, utm_medium, utm_campaign, utm_id;
  end if;

  if to_regclass('public.utm_campaign_report') is null then
    create view public.utm_campaign_report with (security_invoker = true) as
      select utm_source, utm_medium, utm_campaign, utm_content, utm_term,
             count(*) as total_registrations,
             count(*) filter (where paid) as total_paid,
             coalesce(sum(payment_amount) filter (where paid), 0) as total_revenue,
             count(distinct email) as unique_users,
             round(100.0 * count(*) filter (where paid) / nullif(count(*), 0), 2) as conversion_rate,
             round(coalesce(sum(payment_amount) filter (where paid), 0) / nullif(count(*) filter (where paid), 0), 2) as avg_revenue_per_paid_user,
             count(qr_code_id) as registrations_from_qr,
             count(distinct qr_code_id) as unique_qr_codes_used,
             min(created_at) as first_registration_date,
             max(created_at) as last_registration_date
      from (select *, lower(payment_status) in ('captured', 'paid', 'completed', 'success') as paid
            from public.player_registrations) r
      group by utm_source, utm_medium, utm_campaign, utm_content, utm_term;
  end if;

  -- Registrations are matched to a QR code by its id or its short code.
  if to_regclass('public.qr_code_performance') is null then
    create view public.qr_code_performance with (security_invoker = true) as
      select q.id::text as qr_id, q.code as qr_code, q.title as qr_title, q.channel_id as qr_channel,
             q.target_url, q.created_at as qr_created_at,
             coalesce(s.total_scans, 0) as total_scans,
             coalesce(s.unique_scans, 0) as unique_scans,
             coalesce(r.total_registrations, 0) as total_registrations,
             coalesce(r.paid_registrations, 0) as paid_registrations,
             coalesce(r.total_revenue, 0) as total_revenue,
             round(100.0 * coalesce(r.total_registrations, 0) / nullif(s.total_scans, 0), 2) as scan_to_registration_rate,
             round(100.0 * coalesce(r.paid_registrations, 0) / nullif(r.total_registrations, 0), 2) as registration_to_payment_rate
      from public.sspl_qr_codes q
      left join (select qr_code_id, count(*) as total_scans, count(distinct ip_address) as unique_scans
                 from public.sspl_qr_analytics group by qr_code_id) s
        on s.qr_code_id in (q.id::text, q.code)
      left join (select qr_code_id, count(*) as total_registrations,
                        count(*) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')) as paid_registrations,
                        coalesce(sum(payment_amount) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')), 0) as total_revenue
                 from public.player_registrations where qr_code_id is not null group by qr_code_id) r
        on r.qr_code_id in (q.id::text, q.code);
  end if;

  if to_regclass('public.unified_tracking_report') is null then
    create view public.unified_tracking_report with (security_invoker = true) as
      with regs as (
        select qr_code_id, utm_source, utm_medium, utm_campaign, utm_content, utm_term,
               count(*) as total_registrations,
               count(*) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')) as total_paid,
               coalesce(sum(payment_amount) filter (where lower(payment_status) in ('captured', 'paid', 'completed', 'success')), 0) as total_revenue,
               count(distinct email) as unique_users,
               min(created_at) as first_registration_date,
               max(created_at) as last_registration_date
        from public.player_registrations
        group by qr_code_id, utm_source, utm_medium, utm_campaign, utm_content, utm_term
      ), scans as (
        select qr_code_id, count(*) as total_qr_scans, count(distinct ip_address) as unique_scan_ips,
               count(*) filter (where user_agent ~* 'mobile|android|iphone') as mobile_scans,
               count(*) filter (where user_agent ~* 'ipad|tablet') as tablet_scans,
               count(*) filter (where user_agent !~* 'mobile|android|iphone|ipad|tablet') as desktop_scans,
               min(scanned_at) as first_scan_date, max(scanned_at) as last_scan_date
        from public.sspl_qr_analytics group by qr_code_id
      )
      select r.qr_code_id, q.title as qr_code_title, q.channel_id as qr_channel, q.target_url as qr_target_url,
             r.utm_source, r.utm_medium, r.utm_campaign, r.utm_content, r.utm_term,
             coalesce(s.total_qr_scans, 0) as total_qr_scans, coalesce(s.unique_scan_ips, 0) as unique_scan_ips,
             coalesce(s.mobile_scans, 0) as mobile_scans, coalesce(s.tablet_scans, 0) as tablet_scans,
             coalesce(s.desktop_scans, 0) as desktop_scans,
             r.total_registrations, r.total_paid, r.total_revenue, r.unique_users,
             round(100.0 * r.total_paid / nullif(r.total_registrations, 0), 2) as conversion_rate,
             round(100.0 * r.total_registrations / nullif(s.total_qr_scans, 0), 2) as scan_to_registration_rate,
             round(100.0 * r.total_paid / nullif(s.total_qr_scans, 0), 2) as scan_to_payment_rate,
             round(r.total_revenue / nullif(r.unique_users, 0), 2) as avg_revenue_per_user,
             s.first_scan_date, s.last_scan_date, r.first_registration_date, r.last_registration_date
      from regs r
      left join public.sspl_qr_codes q on r.qr_code_id in (q.id::text, q.code)
      left join scans s on s.qr_code_id = r.qr_code_id;
  end if;

  if to_regclass('public.trial_view') is null then
    create view public.trial_view with (security_invoker = true) as
      select c.id as candidate_id, c.name, c.mobile, c.phone, c.city, c.state, c.proficiency,
             p.current_level,
             p.l1_called, p.l1_attendance, p.l1_marks, p.l1_result, p.l1_remarks,
             p.l2_called, p.l2_attendance, p.l2_marks, p.l2_result, p.l2_remarks,
             p.l3_called, p.l3_attendance, p.l3_marks, p.l3_result, p.l3_remarks,
             p.final_status, c.created_at, coalesce(p.updated_at, c.updated_at) as updated_at
      from public.trial_candidates c
      left join public.trial_progress p on p.candidate_id = c.id;
  end if;

  if to_regclass('public.v_trials_section_players') is null then
    create view public.v_trials_section_players with (security_invoker = true) as
      select w.workflow_id, w.registration_id, coalesce(w.confirmation_email_sent, false) as confirmation_email_sent,
             w.confirmation_email_sent_at, w.moved_to_trials_at,
             r.full_name, r.email, r.phone, r.date_of_birth::text as date_of_birth, r.position, r.state, r.city,
             r.payment_status, r.payment_amount, r.created_at as registration_date
      from public.player_workflow w
      join public.player_registrations r on r.id = w.registration_id
      where w.workflow_stage = 'trials_section';
  end if;

  if to_regclass('public.v_trials_allocated_players') is null then
    create view public.v_trials_allocated_players with (security_invoker = true) as
      select w.workflow_id, w.registration_id, a.allocation_id, a.allocation_date, a.allocation_time,
             a.allocation_venue, a.allocation_batch, coalesce(a.attendance_status, 'pending') as attendance_status,
             a.attended_at as attendance_marked_at, a.evaluator_notes as allocation_notes,
             coalesce(w.allocated_to_trials_at, a.created_at) as allocated_at,
             r.full_name, r.email, r.phone, r.date_of_birth::text as date_of_birth, r.position, r.state, r.city,
             r.payment_status, r.created_at as registration_date,
             coalesce(t.overall_score, a.overall_score) as overall_score,
             coalesce(t.selection_status, a.selection_status) as selection_status,
             coalesce(t.remarks, a.remarks) as remarks,
             coalesce(t.evaluated_at, a.evaluated_at) as evaluated_at
      from public.player_workflow w
      join public.player_registrations r on r.id = w.registration_id
      join public.trials_allocations a on a.workflow_id = w.workflow_id
      left join public.trial_results t on t.allocation_id = a.allocation_id;
  end if;

  ---------------------------------------------------------------------------
  -- Local-only changes to tables production already has (skipped there)
  ---------------------------------------------------------------------------
  if local_dev then
    -- Every user gets a profile, now and on sign-up, so the admin Users page's
    -- user_roles -> user_profiles embed has a row to join and a foreign key to follow.
    insert into public.user_profiles (id, email)
      select id, email from auth.users on conflict (id) do nothing;
    create or replace function public.local_dev_create_profile() returns trigger
      language plpgsql security definer set search_path = public as $f$
    begin
      insert into public.user_profiles (id, email) values (new.id, new.email) on conflict (id) do nothing;
      return new;
    end $f$;
    create trigger local_dev_create_profile after insert on auth.users
      for each row execute function public.local_dev_create_profile();
    alter table public.user_roles
      add constraint user_roles_user_id_profile_fkey foreign key (user_id) references public.user_profiles (id) on delete cascade;

    -- The admin Settings page saves with an upsert; locally admin_settings was read-only.
    create policy "local dev admins write admin_settings" on public.admin_settings for all to authenticated
      using (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'))
      with check (exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin'));
  end if;
end $$;
